---
- name: install dependencies
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items:
    - python-pycurl
# - name: Add the nodejs repo
#   apt_repository: repo="ppa:chris-lea/node.js"
- name: Install nodejs
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items:
  - python-software-properties
  - python
  - g++
  - make
  - curl
  - gzip
  - git-core
  - libssl-dev
  - pkg-config
  - build-essential
  - npm
  - nodejs-legacy
- command: npm install -g {{ item }}
  with_items:
    - grunt
    - grunt-cli
    - bower
    - gulp
    - less
    - yo
    - generator-karma
    - generator-angular
    - generator-webapp
    - time-grunt
- command: npm install --save-dev grunt-wiredep

