---

# - name: App | Setting Folder Permissions
#   command: chmod -R 755 {{ app.laravel_storage }}

# - name: App | Composer install
#   command: composer install chdir={{ app.laravel_install_dir }}
  
# - name: App | Create copy of .env file
#   command: cp .env.example .env chdir={{ app.laravel_install_dir }}

# - name: App | Create laravel jey
#   command: 'php /vagrant/artisan key:generate'   
  

# Example read-write git checkout from github
- git: repo=ssh://git@github.com:glenrobson/SimpleAnnotationServer.git dest=/vagrant/app